In [209]:
# import libraries
import pandas as pd
# make dataFrame
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_scr','lpa'])

# Regression usecase
    - loss = np.sum(y-y_hat)**2

In [210]:
df

cgpa  profile_scr  lpa
0     8            8    4
1     7            9    5
2     6           10    6
3     5           12    7

In [188]:
import numpy as np

#layer_dim=[2,2,1]

def initialize_layer(layer_dim):
    np.random.seed(3)
    param={}
    l=len(layer_dim)

    for i in range(1,l):
        param['w'+str(i)]=np.ones((layer[i-1],layer[i]))*0.1
        param['b'+str(i)]=np.zeros((layer[i],1))
        
    return param 

In [127]:
# Initialize parameters
parameter=initialize_layer([2,2,1])
parameter

{'w1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [128]:
# take single data point from dataset
x=df[['cgpa','profile_scr']].values[0].reshape(2,1)
y=df['lpa'].values[0]
y

4

In [254]:
def linear_frwrd_algebra(a_prev,w,b):
    z=np.dot(w.T,a_prev)+b
    return z

In [257]:
def forward_prop(x,parameter):
    a=x
    l=len(parameter)//2 # num of layers in NN
    for i in range(1,l+1):
        a_prev=a
        w1=parameter['w'+str(i)]
        b1=parameter['b'+str(i)]
        #print('A'+str(i-1)+":",a_prev)
        #print('w'+str(i)+':',w1)
        #print('b'+str(i)+':',b1)
        
        a=linear_frwrd_algebra(a_prev,w1,b1)
        #print('A'+str(i)+':',a)
        #print("*"*30)
        
    return a_prev,a
    

In [138]:
parameter=initialize_layer([2,2,1])
a1,y_hat=forward_prop(x,parameter)

A0: [[8]
 [8]]
w1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
A1: [[1.6]
 [1.6]]
******************************
A1: [[1.6]
 [1.6]]
w2: [[0.1]
 [0.1]]
b2: [[0.]]
A2: [[0.32]]
******************************


In [207]:
def update_wght_bias(parameter,y,y_hat,a1,x):
    parameter['w2'][0][0]=parameter['w2'][0][0]-(0.001*(-2*(y-y_hat)*a1[0][0]))
    parameter['w2'][1][0]=parameter['w2'][1][0]-(0.001*(-2*(y-y_hat)*a1[1][0]))
    parameter['b2'][0][0]=parameter['b2'][0][0]-(0.001*(-2*(y-y_hat)))
    
    parameter['w1'][0][0]=parameter['w1'][0][0]-(0.001*(-2*(y-y_hat)*parameter['w2'][0][0]*x[0][0]))
    parameter['w1'][0][1]=parameter['w1'][0][1]-(0.001*(-2*(y-y_hat)*parameter['w2'][0][0]*x[1][0]))
    parameter['b1'][0][0]=parameter['b1'][0][0]-(0.001*(-2*(y-y_hat)*parameter['w2'][0][0]))
    
    parameter['w1'][1][0]=parameter['w1'][1][0]-(0.001*(-2*(y-y_hat)*parameter['w2'][1][0]*x[0][0]))
    parameter['w1'][1][1]=parameter['w1'][1][1]-(0.001*(-2*(y-y_hat)*parameter['w2'][1][0]*x[1][0]))
    parameter['b1'][1][0]=parameter['b1'][1][0]-(0.001*(-2*(y-y_hat)*parameter['w2'][1][0]))
    
    

In [180]:
update_wght_bias(parameter,y,y_hat,a1,x)

In [181]:
parameter

{'w1': array([[0.13984056, 0.13984056],
        [0.15161656, 0.13325919]]),
 'b1': array([[0.00498007],
        [0.0041574 ]]),
 'w2': array([[0.15888],
        [0.15888]]),
 'b2': array([[0.0368]])}

In [182]:
forward_prop(x,parameter)

A0: [[8]
 [8]]
w1: [[0.13984056 0.13984056]
 [0.15161656 0.13325919]]
b1: [[0.00498007]
 [0.0041574 ]]
A1: [[2.33663708]
 [2.18895544]]
******************************
A1: [[2.33663708]
 [2.18895544]]
w2: [[0.15888]
 [0.15888]]
b2: [[0.0368]]
A2: [[0.75582614]]
******************************


(array([[2.33663708],
        [2.18895544]]),
 array([[0.75582614]]))

In [260]:
parameter=initialize_layer([2,2,1])
epochs=15
for i in range(epochs):
    loss=[]
    for j in range(df.shape[0]):
        x=df[['cgpa','profile_scr']].values[j].reshape(2,1)
        y=df['lpa'].values[j]
    
        a1,y_hat=forward_prop(x,parameter)
        y_hat=y_hat[0][0]
    
        update_wght_bias(parameter,y,y_hat,a1,x)
        loss.append((y-y_hat)**2)
        
    print('epoch -',i+1,'loss -',np.array(loss).mean())
    
parameter    
    

epoch - 1 loss - 26.28249792398698
epoch - 2 loss - 19.438253848220803
epoch - 3 loss - 10.139874435827522
epoch - 4 loss - 3.385561305106485
epoch - 5 loss - 1.3198454128484567
epoch - 6 loss - 1.1524956147582675
epoch - 7 loss - 1.2167000755723487
epoch - 8 loss - 1.2516160752948002
epoch - 9 loss - 1.263953264796692
epoch - 10 loss - 1.267990188919891
epoch - 11 loss - 1.2693870298130567
epoch - 12 loss - 1.269994236160704
epoch - 13 loss - 1.270385848419152
epoch - 14 loss - 1.2707366990252273
epoch - 15 loss - 1.2710994592311726


{'w1': array([[0.23663375, 0.45774529],
        [0.24570952, 0.49708601]]),
 'b1': array([[0.02953469],
        [0.0323608 ]]),
 'w2': array([[0.43026095],
        [0.51398611]]),
 'b2': array([[0.11900405]])}

# By using keras library

In [212]:
df

cgpa  profile_scr  lpa
0     8            8    4
1     7            9    5
2     6           10    6
3     5           12    7

In [214]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [215]:
model=Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [216]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [218]:
model.get_weights()

[array([[-0.11764264, -0.46173888],
        [-0.07439065,  0.69865084]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.23408  ],
        [ 1.0060426]], dtype=float32),
 array([0.], dtype=float32)]

In [244]:
new_weights=[np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
            np.array([0.,0.],dtype=np.float32),
            np.array([[0.1],[0.1]],dtype=np.float32),
            np.array([0.],dtype=np.float32)]

In [246]:
new_weights

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [247]:
model.set_weights(new_weights)

In [252]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [261]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=20,verbose=1,batch_size=1)

Epoch 1/20
4/4 [==============================] - 0s 5ms/step - loss: 1.0349
Epoch 2/20
4/4 [==============================] - 0s 5ms/step - loss: 1.0296
Epoch 3/20
4/4 [==============================] - 0s 5ms/step - loss: 1.0297
Epoch 4/20
4/4 [==============================] - 0s 5ms/step - loss: 1.0240
Epoch 5/20
4/4 [==============================] - 0s 5ms/step - loss: 1.0295
Epoch 6/20
4/4 [==============================] - 0s 5ms/step - loss: 1.0224
Epoch 7/20
4/4 [==============================] - 0s 5ms/step - loss: 1.0197
Epoch 8/20
4/4 [==============================] - 0s 6ms/step - loss: 1.0160
Epoch 9/20
4/4 [==============================] - 0s 6ms/step - loss: 1.0146
Epoch 10/20
4/4 [==============================] - 0s 5ms/step - loss: 1.0118
Epoch 11/20
4/4 [==============================] - 0s 5ms/step - loss: 1.0100
Epoch 12/20
4/4 [==============================] - 0s 6ms/step - loss: 1.0070
Epoch 13/20
4/4 [==============================] - 0s 5ms/step - loss: 1.

# Classification usecase
     loss= -ylog(y_hat)-(1-y)log(y_hat) Binary cross entropy
     loss= -t(i)log(p(i)) t(i) =truth, p(i)=class probability,categorical_cross_entropy

In [264]:
df=pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]],columns=['cgpa','profile_scr','placed'])

In [265]:
df

cgpa  profile_scr  placed
0     8            8       1
1     7            9       1
2     6           10       0
3     5            5       0

In [266]:
parameter=initialize_layer([2,2,1])

In [267]:
parameter

{'w1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [268]:
def sigmoid(z):
    a=1/(1+np.exp(-z))
    return a

In [269]:
def linear_frwrd_algebra(a_prev,w,b):
    z=np.dot(w.T,a_prev)+b
    a=sigmoid(z)
    return a

In [270]:
def forward_prop(x,parameter):
    a=x
    l=len(parameter)//2 # num of layers in NN
    for i in range(1,l+1):
        a_prev=a
        w1=parameter['w'+str(i)]
        b1=parameter['b'+str(i)]
        #print('A'+str(i-1)+":",a_prev)
        #print('w'+str(i)+':',w1)
        #print('b'+str(i)+':',b1)
        
        a=linear_frwrd_algebra(a_prev,w1,b1)
        #print('A'+str(i)+':',a)
        #print("*"*30)
        
    return a_prev,a

In [271]:
def update_wght_bias(parameter,y,y_hat,a1,x):
    parameter['w2'][0][0]=parameter['w2'][0][0]-(0.001*(-(y-y_hat)*a1[0][0]))
    parameter['w2'][1][0]=parameter['w2'][1][0]-(0.001*(-(y-y_hat)*a1[1][0]))
    parameter['b2'][0][0]=parameter['b2'][0][0]-(0.001*(-(y-y_hat)))
    
    parameter['w1'][0][0]=parameter['w1'][0][0]-(0.001*(-(y-y_hat)*parameter['w2'][0][0]*a1[0][0]*(1-a1[0][0])*x[0][0]))
    parameter['w1'][0][1]=parameter['w1'][0][1]-(0.001*(-2*(y-y_hat)*parameter['w2'][0][0]*a1[1][0]*(1-a1[1][0])*x[1][0]))
    parameter['b1'][0][0]=parameter['b1'][0][0]-(0.001*(-2*(y-y_hat)*parameter['w2'][0][0]*a1[0][0]*(1-a1[0][0])))
    
    parameter['w1'][1][0]=parameter['w1'][1][0]-(0.001*(-2*(y-y_hat)*parameter['w2'][1][0]*a1[1][0]*(1-a1[1][0])*x[0][0]))
    parameter['w1'][1][1]=parameter['w1'][1][1]-(0.001*(-2*(y-y_hat)*parameter['w2'][1][0]*a1[1][0]*(1-a1[1][0])*x[1][0]))
    parameter['b1'][1][0]=parameter['b1'][1][0]-(0.001*(-2*(y-y_hat)*parameter['w2'][1][0]*a1[1][0]*(1-a1[1][0])))
    

In [275]:
parameter=initialize_layer([2,2,1])
epochs=20
for i in range(epochs):
    loss=[]
    for j in range(df.shape[0]):
        x=df[['cgpa','profile_scr']].values[j].reshape(2,1)
        y=df['placed'].values[j]
    
        a1,y_hat=forward_prop(x,parameter)
        y_hat=y_hat[0][0]
    
        update_wght_bias(parameter,y,y_hat,a1,x)
        loss.append(-y*np.log(y_hat)-(1-y)*np.log(y_hat))
        
    print('epoch -',i+1,'loss -',np.array(loss).mean())
    
parameter    
    

epoch - 1 loss - 0.6152400231320512
epoch - 2 loss - 0.6153785522860074
epoch - 3 loss - 0.615516760632251
epoch - 4 loss - 0.6156546489372986
epoch - 5 loss - 0.6157922179657279
epoch - 6 loss - 0.6159294684801842
epoch - 7 loss - 0.6160664012413839
epoch - 8 loss - 0.6162030170081206
epoch - 9 loss - 0.6163393165372694
epoch - 10 loss - 0.6164753005837916
epoch - 11 loss - 0.6166109699007404
epoch - 12 loss - 0.616746325239265
epoch - 13 loss - 0.6168813673486158
epoch - 14 loss - 0.6170160969761493
epoch - 15 loss - 0.6171505148673333
epoch - 16 loss - 0.6172846217657512
epoch - 17 loss - 0.6174184184131066
epoch - 18 loss - 0.6175519055492292
epoch - 19 loss - 0.6176850839120791
epoch - 20 loss - 0.617817954237751


{'w1': array([[0.09997329, 0.09925882],
        [0.09995129, 0.09925881]]),
 'b1': array([[-0.00020658],
        [-0.00020635]]),
 'w2': array([[0.09842863],
        [0.09842915]]),
 'b2': array([[-0.00318518]])}

In [277]:
model=Sequential()

model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

In [279]:
new_weights=[np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
            np.array([0.,0.],dtype=np.float32),
            np.array([[0.1],[0.1]],dtype=np.float32),
            np.array([0.],dtype=np.float32)]

In [280]:
model.set_weights(new_weights)

In [285]:
optimizer=keras.optimizers.Adam(learning_rate=0.0001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [286]:
model.fit(df.iloc[:,0:-1].values,df.iloc[:,-1].values,epochs=20,verbose=1,batch_size=1)

Epoch 1/20
4/4 [==============================] - 4s 16ms/step - loss: 0.6934
Epoch 2/20
4/4 [==============================] - 0s 24ms/step - loss: 0.6933
Epoch 3/20
4/4 [==============================] - 0s 15ms/step - loss: 0.6933
Epoch 4/20
4/4 [==============================] - 0s 17ms/step - loss: 0.6933
Epoch 5/20
4/4 [==============================] - 0s 18ms/step - loss: 0.6933
Epoch 6/20
4/4 [==============================] - 0s 18ms/step - loss: 0.6934
Epoch 7/20
4/4 [==============================] - 0s 18ms/step - loss: 0.6933
Epoch 8/20
4/4 [==============================] - 0s 16ms/step - loss: 0.6933
Epoch 9/20
4/4 [==============================] - 0s 19ms/step - loss: 0.6933
Epoch 10/20
4/4 [==============================] - 0s 18ms/step - loss: 0.6934
Epoch 11/20
4/4 [==============================] - 0s 18ms/step - loss: 0.6933
Epoch 12/20
4/4 [==============================] - 0s 24ms/step - loss: 0.6933
Epoch 13/20
4/4 [==============================] - 0s 18ms/st